# Generated by Django 5.0.1 on 2024-02-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0003_alter_doctor_meet_link_review"),
        ("patient", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_Type",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=20,
                    ),
                ),
                (
                    "appointment_Stutas",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Running", "Running"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("synptom", models.TextField()),
                ("cancel", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.availabletime",
                    ),
                ),
            ],
        ),
    ]
