# Generated by Django 5.0.1 on 2024-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="availabletime",
        ),
        migrations.AddField(
            model_name="doctor",
            name="availabletime",
            field=models.ManyToManyField(to="doctor.availabletime"),
        ),
    ]
