# Generated by Django 5.0.1 on 2024-02-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_remove_doctor_availabletime_doctor_availabletime"),
        ("patient", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="meet_link",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("⭐", "⭐"),
                            ("⭐⭐", "⭐⭐"),
                            ("⭐⭐⭐", "⭐⭐⭐"),
                            ("⭐⭐⭐⭐", "⭐⭐⭐⭐"),
                            ("⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
